## Optional: i2c port for extra room ENV IV sensor
## https://shop.m5stack.com/products/env-iv-unit-with-temperature-humidity-air-pressure-sensor-sht40-bmp280
i2c:
  - id: bus_a
    sda: GPIO2
    scl: GPIO1

sensor:
  - platform: sht3xd
    temperature:
      name: ${ext_temperature}
      id: room_temperature
      device_class: temperature
      state_class: measurement 
      icon: mdi:thermometer
    humidity:
      name: ${ext_humidity}
      id: room_humidity
      device_class: humidity
      state_class: measurement 
      icon: mdi:water-percent
    i2c_id: bus_a #or choose bus_b
    address: 0x44
    update_interval: 30s

  - platform: qmp6988
    pressure:
      name: ${ext_atm_pressure}
      id: room_pressure
      device_class: atmospheric_pressure
      state_class: measurement 
      oversampling: 16x
      icon: mdi:thermometer-lines
    i2c_id: bus_a #or choose bus_b
    address: 0x70
    update_interval: 30s
    iir_filter: 2x

  - platform: template
    id: room_dewpoint
    name: ${ext_dewpoint}
    device_class: temperature
    state_class: measurement 
    lambda: |-
        return (243.5*(log(id(room_humidity).state/100)+((17.67*id(room_temperature).state)/
        (243.5+id(room_temperature).state)))/(17.67-log(id(room_humidity).state/100)-
        ((17.67*id(room_temperature).state)/(243.5+id(room_temperature).state))));
    unit_of_measurement: °C
    update_interval: 30s
    icon: mdi:thermometer-water

## Override the room temperature from AC with external value from sensor connected to I2C grove port
select:
  - id: update_temp_i2c
    name: ${ext_temperature_control}
    icon: mdi:chart-bell-curve-cumulative
    platform: template
    options:
      - "${ext_mhi}"
      - "${ext_external}"
    initial_option: "${ext_mhi}"
    optimistic: true
    restore_value: true
    entity_category: config
    update_interval: never

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - lambda: 'return id(update_temp_i2c).state == "${ext_external}";'
          then:
            - lambda: |-
                return ((MhiAcCtrl*)id(${deviceid}))->set_room_temperature(id(room_temperature).state);