## Optional: i2c port for extra room KMeter Iso thermocouple
## https://docs.m5stack.com/en/unit/KMeterISO%20Unit
i2c:
  - id: bus_a
    sda: GPIO2
    scl: GPIO1

sensor:
  - platform: kmeteriso
    temperature:
      name: ${room_name} temperature
      id: room_temperature
#    internal_temperature:
#      name: Internal temperature
      device_class: temperature
      state_class: measurement
      filters:
        - median
    update_interval: 30s
    i2c_id: bus_a

## Override the room temperature from AC with external value from sensor connected to I2C grove port
select:
  - id: update_temp_i2c
    name: Temperature Control
    platform: template
    options:
      - "Mhi"
      - "External"
    initial_option: "Mhi"
    optimistic: true
    restore_value: true
    entity_category: config
    update_interval: never

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - lambda: 'return id(update_temp_i2c).state == "External";'
          then:
            - lambda: |-
                return ((MhiAcCtrl*)id(${deviceid}))->set_room_temperature(id(room_temperature).state);
