substitutions:
  restart: ESP Herstart
  defrost: Ontdooien
  status: Status
  framesize: Frame grootte
  error_code: Fout code
  outdoor_temperature: Buiten temperatuur
  return_air_temperature: Binnenunit retour temperatuur
  outdoor_unit_fan_speed: Buitenunit fansnelheid
  indoor_unit_fan_speed: Binnenunit fansnelheid
  current_power: Vermogen
  compressor_frequency: Compressor frequentie
  indoor_unit_total_run_time: Binnenunit draaiuren
  compressor_total_run_time: Buitenunit draaiuren
  vanes_up_down: Lamellen op en neer
  up: Boven
  up_center: Boven midden
  center_down: Midden onder
  down: Onder
  swing: Bewegen
  energy_used: Energie verbruikt
  indoor_u_bend_he_temp_1: Binnen U-bocht HE temp 1
  indoor_capillary_he_temp_2: Binnen Capilair HE temp 2
  indoor_suction_header_he_temp_3: Binnen zuigheader HE temp 3
  outdoor_he_temp: Buiten HE temp
  outdoor_unit_exp_valve: Buitenunit exp klep
  outdoor_unit_discharge_pipe: Buitenunit afvoerleiding
  outdoor_unit_discharge_pipe_super_heat: Buitenunit afvoerleiding oververh.
  compressor_protection_code: Compressor beschermings code
  vanes_left_right: Lamellen links rechts
  left: Links
  left_center: Links midden
  center: Midden
  center_right: Midden rechts
  right: Rechts
  wide: Breed
  spot: Spot
  d_auto: 3D Auto
  compressor_protection_status: Compressor beschermings status
  fan_control_left_right: Lamellen links rechts 
  fan_control_up_down: Lamellen op en neer
  operation: Meetgegevens
  control: Bediening